spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/casino
    username: casino_admin
    password: 123456
    drive-class-name: org.postgresql.Driver

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE